// <auto-generated />
namespace BackgroundJobAndNotificationsDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Upgrade_To_Module_Zero_0_7_6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upgrade_To_Module_Zero_0_7_6));
        
        string IMigrationMetadata.Id
        {
            get { return "201512241146128_Upgrade_To_Module_Zero_0_7_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
