// <auto-generated />
namespace BackgroundJobAndNotificationsDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Revised_Notification_Entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Revised_Notification_Entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201601262132550_Revised_Notification_Entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
